### ISSUE TITLE
Search page might throw an error

### ISSUE THREAD

**Issue by crissdev** [shprink/trendingdevs.com#9]
Searching by City with just a few letters will throw an error. I've noticed the button gets enabled / disabled after a delay. So pressing <ENTER> before it gets disabled the following error is thrown:

```
TypeError: Cannot read property 'ignoreCase' of undefined
    at e.o.value (http://trendingdevs.com/bundle-f62d93.js:11:26845)
    at a [as submit] (http://trendingdevs.com/bundle-f62d93.js:231:6010)
    at fn (eval at <anonymous> (http://trendingdevs.com/bundle-f62d93.js:178:18724), <anonymous>:4:280)
    at o (http://trendingdevs.com/bundle-f62d93.js:179:5882)
    at m.$eval (http://trendingdevs.com/bundle-f62d93.js:177:5605)
    at m.$apply (http://trendingdevs.com/bundle-f62d93.js:177:5835)
    at HTMLFormElement.<anonymous> (http://trendingdevs.com/bundle-f62d93.js:179:5934)
    at HTMLFormElement.We.n (http://trendingdevs.com/bundle-f62d93.js:175:16346)
```

I think I can make an animated GIF if necessary

**Comment by shprink** [comment]
I can reproduce, good catch! Thanks :+1:
